[package]
name = "dag-cbor"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
failure = "0.1"
libipld-base = { path = "../base" }

[dev-dependencies]
libipld-macro = { path = "../macro" }
